config/routes.rb
OnboardApp::Application.routes.draw do
  resources :directorships

  resources :directors

  root to: "companies#index"

  resources :companies do
    get 'import_directors', to: "companies#import_directors"
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :currency, :description, :duedil_co_url, :duedil_locale, :email, :employee_count, :incorporation_date, :name, :phone, :reg_address1, :reg_address2, :reg_address3, :reg_address4, :reg_address_postcode, :reg_co_num, :shareholders_funds, :turnover, :website, :turnover, :shareholders_funds, :directorships_attributes, :directors_attributes

  has_many :directorships
  has_many :directors, through: :directorships
  validates :name, presence: true
  validates :reg_co_num, uniqueness: true
  validates :reg_co_num, presence: true
  validates :duedil_co_url, uniqueness: :true
  before_destroy :delete_directorships
  accepts_nested_attributes_for :directorships, allow_destroy: true
  accepts_nested_attributes_for :directors, allow_destroy: true

    def delete_directorships
      Directorship.where(company_id: self.id).each {|directorship| directorship.destroy}
    end



    def self.duedil_search(name, limit)
        response = Duedil.company_search(name, limit)

        if response
            response["data"].map do |item|
                if item['locale']
                    item['locale'] = item['locale'].upcase
                    { label: "#{item['name']} (#{item['id']} / #{item['locale']})",
                    value: item }
                else
                    { label: "#{item['name']} (#{item['id']})",
                    value: item }
                end
            end
        end
  end

  def self.autopopulate_fields(duedil_co_url)
    company_hash = {}
    key_company_info = Futuroscope::Future.new{ Duedil.get(duedil_co_url)}
    registered_address = Futuroscope::Future.new{ Duedil.get("#{duedil_co_url}/registered-address")}


    if key_company_info.future_value
        company_hash[:duedil_co_url] = duedil_co_url
        duedil_co_url[20] == "u" ? company_hash[:locale] = "UK" : company_hash[:locale] = "ROI"
        company_hash[:reg_co_num] = key_company_info["id"]
        company_hash[:name] = key_company_info["name"]
        company_hash[:description] = key_company_info["description"]
        company_hash[:incorporation_date] = key_company_info["incorporation_date"]
        company_hash[:currency] =  key_company_info["accounts_currency"].upcase if key_company_info["accounts_currency"]
        company_hash [:status] = key_company_info["status"]
        company_hash [:employee_count] = key_company_info["accounts_no_of_employees"]
        company_hash[:turnover] = key_company_info["accounts_turnover"]
        company_hash[:shareholders_funds] = key_company_info["accounts_shareholder_funds"]
    end
    if registered_address.future_value
        company_hash[:website] = registered_address["website"]
        company_hash[:email] = registered_address["email"]
        company_hash[:reg_address1] = registered_address["address1"]
        company_hash[:reg_address2] = registered_address["address2"]
        company_hash[:reg_address3] = registered_address["address3"]
        company_hash[:reg_address4] = registered_address["address4"]
        company_hash[:reg_address_postcode] = registered_address["postcode"]
        company_hash[:phone] = registered_address["phone"]
    end
    company_hash

  end

  def self.existing_record(url)
    Company.where(duedil_co_url: url).first
  end

  def get_active_directorships
    directors_list = Futuroscope::Future.new {
      directors_response = Duedil.get("#{duedil_co_url}/directors", {limit: 100})
      list = directors_response["data"]
      next_directors_url = directors_response["pagination"]["next_url"]

      while next_directors_url
        response = Duedil.get_page(next_directors_url)
        list << response["data"]
        list.flatten!
        next_directors_url = response["pagination"]["next_url"]
      end
      list
    }

      directorships_list = Futuroscope::Future.new {
        directorships_response= Duedil.get("#{duedil_co_url}/directorships", {limit: 100})
        list = directorships_response["data"]
        next_directorships_url = directorships_response["pagination"]["next_url"]

        while next_directorships_url
          response = Duedil.get_page(next_directorships_url)
          directorships_list << response["data"]
          directorships_list.flatten!
          next_directorships_url = response["pagination"]["next_url"]
        end
        list
      }






    directorships_list.map do |directorship_hash|
      directorship_hash[:director] = directors_list.select {|director_hash| director_hash["director_url"] == directorship_hash["directors_uri"]}[0]
    end

    directorships_list.reject{|director_hash| director_hash["active"] != true}

  end

  def import_directors
    get_active_directorships.each do |directorship_hash|

      director_record = Director.find_or_initialize_by_duedil_director_url(directorship_hash[:director]["director_url"])
      director_record.update_attributes!(
        duedil_id: directorship_hash[:director]["id"],
        forename: directorship_hash[:director]["forename"],
        surname: directorship_hash[:director]["surname"],
        date_of_birth: directorship_hash[:director]["date_of_birth"]
      )

      directorship_record = Directorship.find_or_initialize_by_company_id_and_director_id(self.id, director_record.id)
      directorship_record.update_attributes!(
        duedil_id: directorship_hash["id"],
        active: directorship_hash["active"],
        status: directorship_hash["status"],
        appointment_date: directorship_hash["appointment_date"],
        function: directorship_hash["function"],
        position: directorship_hash["position"],
        address1: directorship_hash["address1"],
        address2: directorship_hash["address2"],
        address3: directorship_hash["address3"],
        address4: directorship_hash["address4"],
        postcode: directorship_hash["postcode"]
      )

    end


  end




end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index

      url = "http://duedil.io/v3/#{params["locale"]}/companies/#{params["reg_co_num"]}".downcase if (params["locale"] && params["reg_co_num"])
      url = params["url"] if params["url"]

      @companies = Company.all unless (params["search_term"] || url)
      @search_results = Company.duedil_search(params["search_term"], 10)  if params["search_term"]

      if url
        existing_record = Company.existing_record(url)
        if existing_record
          if params["check_existing"]
            @autopopulate_fields = {existing_record: true}
            @autopopulate_fields[:name] = existing_record.name
          else
            @autopopulate_fields = Company.autopopulate_fields(url)
            @autopopulate_fields[:existing_record] = true
          end
        else
          @autopopulate_fields = Company.autopopulate_fields(url)
        end
      end

    respond_to do |format|
      format.html # index.html.erb
      if @search_results
        format.json { render json: @search_results }
      elsif @autopopulate_fields
        format.json { render json: @autopopulate_fields}
      end
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    @directorships = @company.get_active_directorships

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
    @editing = true
  end

  def import_directors
    @company = Company.find(params[:company_id])
    @company.import_directors

    respond_to do |format|
      format.js {}
    end

  end


  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
#coding: utf-8
module CompaniesHelper

  def pretty_name_string(company)
    company.name.split.map{|word| word.capitalize}.join(' ')
  end

  def currency(company)
    case company.currency
      when "GBP"
        "£"
      else
        company.currency
      end
  end

  def registered_address_string(line1, line2, line3, line4, postcode)
    [line1, line2, line3, line4, postcode].reject{|element| element.length == 0}.join(', ')
  end

  def one_liner(company)
    company.duedil_locale.blank? ? "#{pretty_name_string(company)} (#{company.reg_co_num})" : "#{pretty_name_string(company)} (#{company.reg_co_num} / #{company.duedil_locale})"
  end


end

app/views/companies/_directors.html.haml
- if @company.directorships.blank?
  = link_to "Import Directors", company_import_directors_path(@company), remote: :true
-else
  %h2
    Directors
  %ul
    - @company.directorships.each do |directorship|
      %li
        = directorship.director_forename
        = directorship.director_surname
        |
        = directorship.director_date_of_birth


  = link_to "Re-import Directors", company_import_directors_path(@company), remote: :true

app/views/companies/_fields.html.haml
= f.fields_for :directors do |dsf|
  .field
    = dsf.label :forename
    = dsf.text_field :forename
  .field
    = dsf.label :surename
    = dsf.text_field :surname
  .field
    = dsf.link_to_remove "Remove"

= f.link_to_add 'Add Director', :directors

app/views/companies/_form.html.haml
#spinner

= nested_form_for(@company) do |f|
  - if @company.errors.any?
    #form_errors.row
      .col-md-12
        .column_padding
          #error_explanation.alert.alert-dismissable.alert-danger
            %button.close{"data-dismiss" => "alert", type: "button"} ×
            %p
              = pluralize(@company.errors.count, "error")
              prohibited this company from being saved:
            %ul
              - @company.errors.full_messages.each do |msg|
                %li= msg
  .row
    .col-md-4
      .column_padding
        %h3 Basic Information
        .field
          = f.label :name, "Company Name", class: "form_label"
          %br/
          = f.text_field :name, :autocomplete => :off
        .field
          = f.label :reg_co_num, "Registered Company Number", class: "form_label"
          %br/
          = f.text_field :reg_co_num, :autocomplete => :off
        .field
          = f.select( :duedil_locale, ["UK", "ROI"], {include_blank: "Country"})
          - unless @editing
            #lookup
              = link_to 'Lookup', new_company_path, class: "btn btn-xs btn-danger"
        .field
          = f.label :incorporation_date, class: "form_label"
          %br/
          = f.text_field :incorporation_date, class: "datepicker", :autocomplete => :off
        .field
          = f.label :description, "Description", class: "form_label"
          %br/
          = f.text_area :description, class: "company_description", :autocomplete => :off
        .field
          = f.label :employee_count,  "Number of Employees", class: "form_label"
          %br/
          = f.text_field :employee_count, :autocomplete => :off
        = f.hidden_field :duedil_co_url

    .col-md-4
      .column_padding
        %h3 Registered Address
        .field
          = f.label :reg_address1, "Address Line 1", class: "form_label"
          %br
          = f.text_field :reg_address1, :autocomplete => :off
        .field
          = f.label :reg_address1, "Address Line 2", class: "form_label"
          %br
          = f.text_field :reg_address2, :autocomplete => :off
        .field
          = f.label :reg_address1, "Address Line 3", class: "form_label"
          %br
          = f.text_field :reg_address3, :autocomplete => :off
        .field
          = f.label :reg_address1, "Address Line 4", class: "form_label"
          %br
          = f.text_field :reg_address4, :autocomplete => :off
        .field
          = f.label :reg_address_postcode, "Postcode", class: "form_label"
          %br/
          = f.text_field :reg_address_postcode, :autocomplete => :off

    .col-md-4
      .column_padding
        %h3 Financials
        .field
          = f.select(:currency, ["GBP", "EUR"], {include_blank: "Currency"})
        .field
          = f.label :turnover, class: "form_label"
          %br
          = f.text_field :turnover, :autocomplete => :off
        .field
          = f.label :shareholders_funds, "Shareholders' Funds", class: "form_label"
          %br
          =f.text_field :shareholders_funds, :autocomplete => :off

        %h3 Contact Information
        .field
          = f.label :website, class: "form_label"
          %br/
          = f.text_field :website, :autocomplete => :off
        .field
          = f.label :email, "Email Address", class: "form_label"
          %br/
          = f.text_field :email, :autocomplete => :off
        .field
          = f.label :phone, "Phone Number", class: "form_label"
          %br/
          = f.text_field :phone, :autocomplete => :off



  .row
    .col-md-12
      .column_padding
        .actions
          = f.submit "Submit", class: "btn btn-success button_position"
          - if @editing
            - unless @company.duedil_co_url.blank?
              = link_to 'DueDil Refresh', edit_company_path(@company), class: "btn btn-danger button_position data_refresh"

app/views/companies/edit.html.haml
.row
  .col-md-12
    .column_padding
      %h1.editing Edit Company Details
= render 'form'
.row
  .col-md-12
    .column_padding
      .actions.page_bottom
        = link_to 'Show', @company, class: "btn btn-primary button_position"
        = link_to 'Back', companies_path, class: "btn btn-default button_position"

app/views/companies/import_directors.js.erb
$('#directors').html("<%= escape_javascript(render 'directors') %>");

app/views/companies/index.html.haml
.row
  .col-md-12
    .column_padding
      %h1 Company List
      - @companies.each do |company|
        %h4
          = one_liner(company)
          = link_to 'Show', company, class: "btn btn-xs btn-primary"
          = link_to 'Edit', edit_company_path(company), class: "btn btn-xs btn-info"
          = link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger"
.row
  .col-md-12
    .column_padding
      .actions.page_bottom
        = link_to 'New Company', new_company_path, class: "btn btn-success button_position"
.footer
  Powered by
  = image_tag 'duedil_logo.jpg', class: "duedil_logo"

app/views/companies/new.html.haml
.row
  .col-md-12
    .column_padding
      %h1 Enter Company Details
= render 'form'
.row
  .col-md-12
    .column_padding
      .actions.page_bottom
        = link_to 'Back', companies_path, class: "btn btn-default button_position"

app/views/companies/show.html.haml
- if flash[:notice]
  #notice.alert.alert-dismissable.alert-success
    %button.close{"data-dismiss" => "alert", type: "button"} ×
    = notice
.row
  .col-md-6
    .column_padding
      %h1
        = pretty_name_string(@company)
      - unless @company.description.blank?
        %h4
          = @company.description

      %p
        ="Company Number: #{@company.reg_co_num}"
        - if @company.duedil_locale
          = "#{@company.duedil_locale.upcase}"
        - unless @company.incorporation_date.blank?
          %br
          = "Incorporated: #{@company.incorporation_date.to_formatted_s(:long_ordinal)}"
        - unless registered_address_string(@company.reg_address1, @company.reg_address2, @company.reg_address3, @company.reg_address4, @company.reg_address_postcode).blank?
          %br
            ="Registered Address: #{registered_address_string(@company.reg_address1, @company.reg_address2, @company.reg_address3, @company.reg_address4, @company.reg_address_postcode)}"
      - unless @company.website.blank?
        %h3
          =@company.website.downcase

      - unless @company.email.blank?
        ="Email: #{@company.email.downcase}"
        %br
      - unless @company.phone.blank?
        ="Phone: #{@company.phone}"



      - unless @company.shareholders_funds.blank?
        %h4
          Shareholders Funds:
          = "#{currency(@company)}#{financials(@company.shareholders_funds)}"
      - unless @company.turnover.blank?
        %h4
          Turnover:
          = "#{currency(@company)}#{financials(@company.turnover)}"
      - unless @company.employee_count.blank?
        %h4
          Employees:
          = @company.employee_count
  .col-md-6
    #directors.column_padding
      = render 'directors'
.row
  .col-md-12
    .column_padding
      .actions.page_bottom
        = link_to 'Edit', edit_company_path(@company), class: "btn btn-info button_position"
        = link_to 'Back', companies_path, class: "btn btn-default button_position"