config/routes.rb
OnboardApp::Application.routes.draw do
  resources :directorships

  resources :directors

  root to: "companies#index"

  resources :companies do
    get 'import_directors', to: "companies#import_directors"
  end

end

app/models/directorship.rb
class Directorship < ActiveRecord::Base
  attr_accessible :company_id, :director_id, :director_forename, :duedil_id, :active, :status, :appointment_date, :function, :position, :address1, :address2, :address3, :address4, :address5, :postcode
  belongs_to :director
  belongs_to :company

  validates :company_id, :uniqueness => { :scope => :director_id }


  def director_forename
    director.forename if director
  end

  def director_forename=(forename)
    self.director = Director.find_or_create_by_forename(forename) unless forename.blank?
  end

  def director_date_of_birth
    director.date_of_birth if director
  end

  def director_surname
    director.surname if director
  end

end
#

app/controllers/directorships_controller.rb
class DirectorshipsController < ApplicationController
  # GET /directorships
  # GET /directorships.json
  def index
    @directorships = Directorship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @directorships }
    end
  end

  # GET /directorships/1
  # GET /directorships/1.json
  def show
    @directorship = Directorship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @directorship }
    end
  end

  # GET /directorships/new
  # GET /directorships/new.json
  def new
    @directorship = Directorship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @directorship }
    end
  end

  # GET /directorships/1/edit
  def edit
    @directorship = Directorship.find(params[:id])
  end

  # POST /directorships
  # POST /directorships.json
  def create
    @directorship = Directorship.new(params[:directorship])

    respond_to do |format|
      if @directorship.save
        format.html { redirect_to @directorship, notice: 'Directorship was successfully created.' }
        format.json { render json: @directorship, status: :created, location: @directorship }
      else
        format.html { render action: "new" }
        format.json { render json: @directorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /directorships/1
  # PUT /directorships/1.json
  def update
    @directorship = Directorship.find(params[:id])

    respond_to do |format|
      if @directorship.update_attributes(params[:directorship])
        format.html { redirect_to @directorship, notice: 'Directorship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @directorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directorships/1
  # DELETE /directorships/1.json
  def destroy
    @directorship = Directorship.find(params[:id])
    @directorship.destroy

    respond_to do |format|
      format.html { redirect_to directorships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/directorships_helper.rb
module DirectorshipsHelper
end

app/views/directorships/_form.html.erb
<%= form_for(@directorship) do |f| %>
  <% if @directorship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directorship.errors.count, "error") %> prohibited this directorship from being saved:</h2>

      <ul>
      <% @directorship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :director %><br />
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directorships/edit.html.erb
<h1>Editing directorship</h1>

<%= render 'form' %>

<%= link_to 'Show', @directorship %> |
<%= link_to 'Back', directorships_path %>

app/views/directorships/index.html.erb
<h1>Listing directorships</h1>

<table>
  <tr>
    <th>Director</th>
    <th>Company</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @directorships.each do |directorship| %>
  <tr>
    <td><%= directorship.director %></td>
    <td><%= directorship.company %></td>
    <td><%= link_to 'Show', directorship %></td>
    <td><%= link_to 'Edit', edit_directorship_path(directorship) %></td>
    <td><%= link_to 'Destroy', directorship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Directorship', new_directorship_path %>

app/views/directorships/new.html.erb
<h1>New directorship</h1>

<%= render 'form' %>

<%= link_to 'Back', directorships_path %>

app/views/directorships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Director:</b>
  <%= @directorship.director %>
</p>

<p>
  <b>Company:</b>
  <%= @directorship.company %>
</p>


<%= link_to 'Edit', edit_directorship_path(@directorship) %> |
<%= link_to 'Back', directorships_path %>